# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20170227_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hired',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
