# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratingstr',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
