# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review_ratingstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratingstr',
            field=models.CharField(default='', max_length=10),
        ),
    ]
