# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170226_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratingemptystr',
            field=models.CharField(default='', max_length=10),
        ),
    ]
