# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_by', models.ManyToManyField(related_name='like', to='login_register.User')),
                ('post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='login_register.User')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
