# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:32
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistManager',
        ),
        migrations.AlterModelManagers(
            name='wishlist',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
